[package]
name = "cel-rs"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.1"

[build-dependencies]
lalrpop = "0.16.2"

